JobPortal/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('home.urls')),
                  path('custom/', include('custom_auth.urls')),
                  path('cms/', include('cms.urls')),
                  path('company/', include('company.urls')),
                  path('jobseeker/', include('jobseeker.urls')),
                  path('blog/',include('blog.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cms/urls.py
from django.urls import path
from .views import *

app_name = 'cms'

urlpatterns = [

    path('', AboutUsView.as_view(), name='about'),
    path('contact/', ContactUsView.as_view(), name='contact'),

]

home/urls.py
from django.urls import path
from home.views import *

app_name = "home"

urlpatterns = [

    path('', IndexView.as_view(), name='home'),
    path('search/', SearchView.as_view(), name='search'),
    path('faq/', FaqView.as_view(), name='faq'),
    path('jobdetail/<slug:slug>/', JobDetailView.as_view(), name='jobdetail'),
    path('list/', JobListView.as_view(), name='joblist'),
    path('location/<slug:slug>',ByLocationView.as_view(),name='by_location')


]

templates/partials/search.html
<form action="{% url 'home:search' %}" class="serach-form-area">

                        <div class="row justify-content-center form-wrap">
                            <div class="col-lg-4 form-cols">
                                <input type="text" class="form-control" name="title"
                                       placeholder="what are you looging for?" id="title">
                            </div>
                            <div class="col-lg-3 form-cols">
                                <input type="text" class="form-control" name="location"
                                       placeholder="where are you looking for?" id="location">
                            </div>
                            <div class="col-lg-3 form-cols">
                                <input type="text" class="form-control" name="category"
                                       placeholder="category?" id="category">
                            </div>
                            <div class="col-lg-2 form-cols">
                                <button type="submit" class="btn btn-info">
                                    <span class="lnr lnr-magnifier"></span> Search
                                </button>
                            </div>
                        </div>
                    </form>

templates/partials/sidebar_general.html
{% load thumbnail %}
<div class="single-slidebar">
    <h4>Jobs by Location</h4>
    <ul class="cat-list">
        {% for i in jbl %}



            <li><a class="justify-content-between d-flex" href="{% url 'home:by_location' i.district %}"><p>{{ i.district }}</p> <span>{{ i.count }}</span>
            </a></li>
        {% endfor %}


    </ul>
</div>

<div class="single-slidebar">
    <h4 style="color: #795fff">Popular job posts</h4>
    <div class="active-relatedjob-carusel">
        {% for t in top_rated %}
            <div class="single-rated">

                {% thumbnail t.company.company_image "250x150" crop="center" as im %}
                    <img  src="{{ im.url }}" >
                {% endthumbnail %}

                <a href="{% url 'home:jobdetail' t %}"><h3>{{ t.job_title }}</h3></a><br>
                <h5><em>{{ t.company.company_name }}</em></h5><hr>

                <h4 class="fa fa-group mb-2"> No of Vacancy:&nbsp;{{ t.vacancy }}</h4><br>
                <h4 class="fa fa-list-alt mb-2"> Category:&nbsp;{{ t.category }}</h4><br>
                <h4 class="fa fa-braille mb-2"> Experience:&nbsp;{{ t.experience }}</h4><br>

            </div>
        {% endfor %}

    </div>
</div>