JobPortal/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('home.urls')),
                  path('custom/', include('custom_auth.urls')),
                  path('cms/', include('cms.urls')),
                  path('company/', include('company.urls')),
                  path('jobseeker/', include('jobseeker.urls')),
                  path('blog/',include('blog.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cms/urls.py
from django.urls import path
from .views import *

app_name = 'cms'

urlpatterns = [

    path('', AboutUsView.as_view(), name='about'),
    path('contact/', ContactUsView.as_view(), name='contact'),

]

custom_auth/urls.py
from django.urls import path

from custom_auth.views import *

app_name = 'custom_auth'

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('register/', RegistrationView.as_view(), name='register'),

    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('password_reset', UserPasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done', UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>', UserPasswordResetConfirmView.as_view(), name='password_reset_confirmok'),
    path('activate/<uidb64>/<token>',activate, name='activate'),
    path('activationdone/',ActivationDoneView.as_view(),name='activation_complete')

]

home/urls.py
from django.urls import path
from home.views import *

app_name = "home"

urlpatterns = [

    path('', IndexView.as_view(), name='home'),
    path('search/', SearchView.as_view(), name='search'),
    path('faq/', FaqView.as_view(), name='faq'),
    path('jobdetail/<slug:slug>/', JobDetailView.as_view(), name='jobdetail'),
    path('list/', JobListView.as_view(), name='joblist'),
    path('location/<slug:slug>',ByLocationView.as_view(),name='by_location')


]

jobseeker/urls.py
from django.urls import path

from jobseeker import views
from jobseeker.views import *

app_name = "jobseeker"

urlpatterns = [

    path('category/', JobSeekerCategoryView.as_view(), name='jobcategory'),

    path('seekerdetail/', JobSeekerDetailView.as_view(), name='seekerdetail'),
    path('seekertable/', JobsekkerTableView.as_view(), name='table'),
    path('seekerdashboard/', SeekerDashboardView.as_view(), name='sdhome'),
    path('seekerdashboard/base', SeekerIndexView.as_view(), name='sindex'),
    path('seekerdetail/<slug:slug>/update', UserProfileUpdateView.as_view(), name='supdate'),
    path('change_password/', ChangePassword.as_view(), name='password-change'),
    path('ajax/load-dis/', views.load_province, name='job_ajax_load_district'),

]

jobseeker/models.py
from django.utils.text import slugify
from sorl.thumbnail import ImageField

from custom_auth.models import User
from django.db import models
from home.models import *

# Create your models here.
from home.validators import *


class Jobseeker(models.Model):
    name = models.CharField(max_length=100, validators=[name_validation])
    dob = models.DateField(validators=[Date_validation])
    gender = models.ForeignKey(Gender, on_delete=models.CASCADE)
    province = models.ForeignKey(Provience, related_name='jobseeker_provience', on_delete=models.CASCADE)
    district = models.ForeignKey(District, related_name='jobseeker_district', on_delete=models.CASCADE)
    address = models.CharField(max_length=50)
    phone_no = models.CharField(blank=True, max_length=9, validators=[phone_validation])
    mobile_no = models.CharField(blank=True, null=True, validators=[mobile_validation], max_length=10)
    education = models.ForeignKey(Education, on_delete=models.CASCADE)
    resume = models.FileField(upload_to='media/')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    photo = ImageField()
    slug = models.SlugField()

    def __str__(self):
        return self.slug

    def save(self, *args, **kwargs):
        value = self.name
        self.slug = slugify(value, allow_unicode=True)
        super().save(*args, **kwargs)

jobseeker/forms.py
from django import forms
from .models import *


class SeekerDetailForm(forms.ModelForm):
    class Meta:
        model = Jobseeker
        fields = ['name', 'dob','province','district', 'address', 'phone_no', 'mobile_no', 'resume', 'photo']

jobseeker/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import PasswordChangeView, PasswordResetView
from django.core.files.storage import FileSystemStorage
from django.shortcuts import render, redirect
from django.urls import reverse_lazy

from .forms import *
from company.models import *

# Create your views here.
from django.views.generic import *
from .models import *

class JobSeekerCategoryView(TemplateView):
    template_name = 'job_category.html'

class JobSeekerDetailView(CreateView):
    template_name = 'seeker_detail.html'
    model = Jobseeker
    form_class = SeekerDetailForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['genders'] = Gender.objects.all()
        context['educations'] = Education.objects.all()


        try:
            context['seeker'] = Jobseeker.objects.get(user_id=self.request.user)
        except Exception as e:
            print(e)

        return context

    def post(self, request, *args, **kwargs):
        # form = self.get_form()
        form = SeekerDetailForm(request.POST, request.FILES)
        print("+++++++++++++++++++++++++++++++++++++++++++++++++++++++++")

        if form.is_valid():

            ge = request.POST.get('gen')
            ed = request.POST.get('edu')

            gender = Gender.objects.get(gender=ge)
            education = Education.objects.get(education=ed)

            sucess = form.save(commit=False)
            sucess.user = request.user
            sucess.education_id = education.id
            sucess.gender_id = gender.id


            sucess.save()

            return redirect('home:joblist')

        else:
            print(form.errors)

        return redirect('jobseeker:sdhome')


class SeekerIndexView(TemplateView):
    template_name = 'seeker dashboard/seeker_index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        try:
            context['seeker'] = Jobseeker.objects.get(user_id=self.request.user)
        except Exception as e:
            print(e)
        return context


class JobsekkerTableView(ListView):
    model = AppliedBySeeker
    template_name = 'seeker dashboard/applied job-table.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user

        context['applybyuser'] = AppliedBySeeker.objects.filter(applicant_name__user_id=user)
        try:
            context['seeker'] = Jobseeker.objects.get(user_id=user)
        except Exception as e:
            print(e)
        return context


class SeekerDashboardView(TemplateView):
    model = Jobseeker
    # template_name = 'jobseeker dashboard/user_dashboard.html'
    template_name = 'seeker dashboard/dashboard2.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:

            context['seeker'] = Jobseeker.objects.get(user_id=self.request.user)
        except Exception as e:
            print(e)
        return context


class UserProfileUpdateView(UpdateView):
    model = Jobseeker
    template_name = 'seeker dashboard/userprofile_update_form.html'
    fields = ['name', 'dob', 'gender', 'province', 'district', 'address', 'phone_no', 'mobile_no', 'education',
              'resume', 'photo']
    success_url = reverse_lazy('jobseeker:sindex')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:

            context['seeker'] = Jobseeker.objects.get(user_id=self.request.user)
        except Exception as e:
            print(e)
        return context


class ChangePassword(PasswordChangeView):
    template_name = 'seeker dashboard/jobseeker_password_change.html'
    success_url = reverse_lazy('jobseeker:sdhome')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:

            context['seeker'] = Jobseeker.objects.get(user_id=self.request.user)
        except Exception as e:
            print(e)
        return context


def load_province(request):
    pro_id = request.GET.get('province')
    districts = District.objects.filter(provience_id=pro_id)
    return render(request, 'seeker dashboard/drop_down_dis_pro.html', {'districts': districts})

jobseeker/templates/seeker dashboard/applied job-table.html
{% extends 'seeker dashboard/dashboard2.html' %}
{% block seeker-content %}
    <!-- Static Table Start -->
    <div class="data-table-area mg-b-15">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="sparkline13-list shadow-reset">
                        <div class="sparkline13-hd">
                            <div class="main-sparkline13-hd">
                                <h1>Projects <span class="table-project-n">Data</span> Table</h1>

                            </div>
                        </div>
                        <div class="sparkline13-graph">
                            <div class="datatable-dashv1-list custom-datatable-overright">

                                <div class="table-responsive">
                                    <table class="table table-bordered" data-toggle="table" data-pagination="true"
                                           data-search="true"
                                           data-show-columns="true" data-show-pagination-switch="true"
                                           data-show-refresh="true" data-key-events="true" data-show-toggle="true"
                                           data-resizable="true" data-cookie="true" data-cookie-id-table="saveId"
                                           data-show-export="true" data-click-to-select="true" data-toolbar="#toolbar">
                                        <thead>
                                        <tr>
                                            <th>Job title</th>
                                            <th>Company name</th>
                                            <th>Position</th>
                                            <th>Category</th>
                                            <th>Applied Date</th>

                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for i in applybyuser %}
                                            <tr>

                                                <td>
                                                    <a href="{% url 'home:jobdetail' i.job_title.slug %}">{{ i.job_title.job_title }}</a>
                                                </td>
                                                <td>{{ i.job_title.company.company_name }}</td>
                                                <td>{{ i.job_title.level_of_job }}</td>
                                                <td>{{ i.job_title.category }}</td>
                                                <td>{{ i.applied_date }}</td>

                                            </tr>
                                        {% endfor %}


                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

jobseeker/templates/seeker dashboard/dashboard.html
<!doctype html>
{% load static %}
{% load thumbnail %}
<html class="no-js" lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Dashboard v.1.0 | Adminpro - Admin Template</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="{% static 'css/jobseeker_style.css' %}">

    <!-- favicon
		============================================ -->
    <link rel="shortcut icon" type="image/x-icon" href="img/favicon.ico">
    <!-- Google Fonts
		============================================ -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i,800" rel="stylesheet">
    <!-- Bootstrap CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'css/bootstraps.min.css' %}">
    <!-- Bootstrap CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <!-- adminpro icon CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'css/adminpro-custon-icon.css' %}">
    <!-- meanmenu icon CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'css/meanmenu.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.mCustomScrollbar.min.css' %}">
    <!-- mCustomScrollbar CSS

    <!-- animate CSS

		============================================ -->
    <link rel="stylesheet" href="{% static 'css/c3.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
    <!-- data-table CSS
		============================================ -->
    <link rel="stylesheet" href="{% static 'css/bootstrap-table.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-editable.css' %}">
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'css/form/all-type-forms.css' %}">
    <link rel="stylesheet" href="{% static 'css/form/themesaller-forms.css' %}">
    <!-- normalize CSS


		============================================ -->
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <!-- responsive CSS

		============================================ -->
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">

    <script src="{% static 'js/vendor/modernizr-2.8.3.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
            integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
            crossorigin="anonymous"></script>
</head>

<body class="materialdesign">
<!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->

<!-- Header top area start-->
<div class="wrapper-pro">
    <div class="left-sidebar-pro">
        <nav id="sidebar">
            <div class="sidebar-header">
                <a href="#">{% thumbnail seeker.photo "150x150" crop="center" as im %}
                    <img src="{{ im.url }}" class="img-circle">
                {% endthumbnail %}
                </a>
                <h3>{{ request.user }}</h3>
                <p>Developer</p>
                <strong>AP+</strong>
            </div>
            <div class="left-custom-menu-adp-wrap">
                <ul class="nav navbar-nav left-sidebar-menu-pro">
                    <li class="nav-item">
                        <a href="{% url 'home:home' %}" aria-expanded="false"><i class="fa big-icon fa-home"></i> <span
                                class="mini-dn">Home</span> </a>

                    </li>
                    <li class="nav-item"><a href="


                            {% if request.user.id == seeker.user_id %}{% url 'jobseeker:supdate' seeker.slug %}{% else %}{% url 'jobseeker:seekerdetail' %} {% endif %}"
                                            aria-expanded="false"><i class="glyphicon glyphicon-user"></i><span
                            class="mini-dn">&nbsp My profile</span> </a>

                    </li>
                    <li class="nav-item"><a href="{% url 'jobseeker:table' %}" aria-expanded="false"><i
                            class="glyphicon glyphicon-list"></i><span
                            class="mini-dn">&nbsp Applied job list</span> </a>

                    </li>
                    <li class="nav-item"><a href="#" aria-expanded="false"><i class="glyphicon glyphicon-bell"></i><span
                            class="mini-dn">&nbsp Notification</span> </a>

                    </li>

                    <li class="nav-item"><a href="{% url 'jobseeker:password-change' %}" aria-expanded="false"><i
                            class="glyphicon glyphicon-key"></i><span
                            class="mini-dn">&nbsp Change Password</span> </a>

                    </li>

                    <li class="nav-item"><a href="{% url 'custom_auth:logout' %}" aria-expanded="false"><i
                            class="glyphicon glyphicon-log-out"></i><span class="mini-dn">&nbsp Logout</span> </a>

                    </li>


                </ul>
            </div>
        </nav>
    </div>
    <div class="content-inner-all">
        <div class="header-top-area">
            <div class="fixed-header-top">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-1 col-md-6 col-sm-6 col-xs-12">
                            <button type="button" id="sidebarCollapse"
                                    class="btn bar-button-pro header-drl-controller-btn btn-info navbar-btn">
                                <i class="fa fa-bars"></i>
                            </button>
                            <div class="admin-logo logo-wrap-pro">
                                <a href="#"><img src="img/logo/log.png" alt=""/>
                                </a>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-1 col-sm-1 col-xs-12">
                            <div class="header-top-menu tabl-d-n">
                                <ul class="nav navbar-nav mai-top-nav">
                                    <li class="nav-item"><a href="#" class="nav-link">Home</a>
                                    </li>
                                    <li class="nav-item"><a href="#" class="nav-link">About</a>
                                    </li>
                                    <li class="nav-item"><a href="#" class="nav-link">Services</a>
                                    </li>

                                </ul>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
        <!-- Header top area end-->

        <div class="mobile-menu-area">

             {% block seeker-content %}{% endblock %}


        </div>
    </div>

    <!-- jquery
        ============================================ -->
    <script src="{% static 'js/vendor/jquery-1.11.3.min.js' %}"></script>
    <!-- bootstrap JS
        ============================================ -->
    <script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
    <!-- meanmenu JS
        ============================================ -->
    <script src="{% static 'js/jquery.meanmenu.js' %}"></script>
    <!-- mCustomScrollbar JS
        ============================================not used -->


    <script src="{% static 'js/jobseekermain.js' %}"></script>
    <script src="{% static 'js/vendor/modernizr-2.8.3.min.js' %}"></script>
</body>

</html>

jobseeker/templates/seeker dashboard/drop_down_dis_pro.html
<option value="">---------</option>
{% for d in districts %}
<option value="{{ d.pk }}">{{ d.district}}</option>
{% endfor %}

jobseeker/templates/seeker dashboard/jobseeker_password_change.html
{% extends "seeker dashboard/dashboard2.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block seeker-content %}


    <div class="container">
        <div class="row justify-content-center align-items-center" style="height:80vh;">
            <div class="col-auto border p-3">
                {% if form.errors %}
                    <p class="bg-danger p-2">Incorrect password</p>
                {% endif %}
                {% if next %}
                    {% if user.is_authenticated %}

                        <p class="bg-warning p-1">Your account doesn't have access.</p>
                    {% else %}
                        <p class="bg-secondary">Please login to see this page.</p>
                    {% endif %}
                {% endif %}
                <div class="col-lg-offset-3 col-lg-6 mt-10" style="margin-top: 75px;">

                    <form method="post" action="{% url 'jobseeker:password-change' %}" >
                        {% csrf_token %}
                        {{ form | crispy }}
                        <input class="mt-3" type="submit" value="Change Password"/>
                        <input type="hidden" name="next" value="{{ next }}"/>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

jobseeker/templates/seeker dashboard/seeker_index.html
{% extends 'seeker dashboard/dashboard2.html' %}
{% load thumbnail %}
{% block seeker-content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-offset-3 col-lg-6" style="text-align: center">
                <h1>WelCome</h1><hr>
                <h5>{{ seeker.name }}</h5>
            </div>

        </div>

    <br>
        <div class="row">
            <div class="col-lg-offset-4 col-lg-4" style="alignment: center">
                {% thumbnail seeker.photo "500x500" as im %}
                    <img src="{{ im.url }}" class="rounded">
                {% endthumbnail %}
            </div>
        </div>
    </div>
{% endblock %}

jobseeker/templates/seeker dashboard/user_dashboard.html
{% extends 'seeker dashboard/dashboard2.html' %}
{% block seeker-content %}
    <style>
        .jack {

            background: rgb(7, 0, 36);
            background: radial-gradient(circle, rgba(7, 0, 36, 1) 0%, rgba(7, 0, 36, 1) 36%, rgba(9, 9, 121, 1) 75%, rgba(0, 212, 255, 1) 100%);
        }

        .jack h1 {
            text-align: center;
            padding: 250px;
            color: #1e7e34;
        }


    </style>
    <div class="jack">
        <h1>Welcome {{ request.user }}<br>Hope you would find best job for you....</h1>

    </div>

{% endblock %}

jobseeker/templates/seeker dashboard/userprofile_update_form.html
{% extends 'seeker dashboard/dashboard2.html' %}
{% load thumbnail %}
{% load crispy_forms_tags %}
{% block seeker-content %}

    <div class="row">
        <div class="col-lg-1"></div>

        <div class="col-md-11 col-lg-7 mb-5">

            <form method="post" enctype="multipart/form-data" id="jobseekerupdateForm" data-updatejob-url="{% url 'jobseeker:job_ajax_load_district' %}">
                {% csrf_token %}
                {{ form |crispy }}
                <input type="submit" value="UPDATE">

            </form>
        </div>

        <div class="col-lg-4">
            <div class="p-4 mb-3 bg-white">

                <h3 style= "text-align: center;">Your Profile</h3>

                {% thumbnail seeker.photo "350x300" crop="center" as im %}
                    <img src="{{ im.url }}" class="img-thumbnail">
                {% endthumbnail %}


            <div class="seeker-profile">

                <p>Name:{{ seeker.name }}</p>

                <p>DOB:{{ seeker.dob }}</p>

                <p>Phone no:{{ seeker.phone_no }}</p>


                <p>Email-ID{{ sekker.user.email }}</p>


            </div>
            </div>


        </div>
    </div>

    <style>
    .seeker-profile{

        padding-top: 30px;


    }
    .seeker-profile p{

        font-style: italic;
        text-align: center;
    }
    </style>



        <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script>
    $("#id_province").change(function () {
      var url = $("#jobseekerupdateForm").attr("data-updatejob-url");  // get the url of the `load_cities` view
      var provinceId = $(this).val();  // get the selected country ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'province': provinceId       // add the country id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_cities` view function
          $("#id_district").html(data);  // replace the contents of the city input with the data that came from the server
        }
      });

    });
  </script>

{% endblock %}