JobPortal/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('home.urls')),
                  path('custom/', include('custom_auth.urls')),
                  path('cms/', include('cms.urls')),
                  path('company/', include('company.urls')),
                  path('jobseeker/', include('jobseeker.urls')),
                  path('blog/',include('blog.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cms/urls.py
from django.urls import path
from .views import *

app_name = 'cms'

urlpatterns = [

    path('', AboutUsView.as_view(), name='about'),
    path('contact/', ContactUsView.as_view(), name='contact'),

]

company/urls.py
from django.urls import path

from company import views
from company.views import *

app_name = 'company'

urlpatterns = [
    path('jobpost/', JobPostView.as_view(), name='jobpost'),
    path('jobpost/c_list', CompanyJobListView.as_view(), name='cjoblist'),
    path('jobpost/chome', CompanyHomeView.as_view(), name='jobhome'),
    path('jobpost/base', CompanyBaseView.as_view(), name='cbase'),
    path('profile/', CompanyProfileView.as_view(), name='cprofile'),

    path('companydetail/', CompanyDetailView.as_view(), name='companydetail'),
    path('companydetail/<slug:slug>/update', CompanyUpdateView.as_view(), name='cupdate'),
    path('apply/', AppliedBySeekerView.as_view(), name='apply'),
    path('jobpost/<slug:slug>/update', JobUpdateView.as_view(), name='jobupdate'),
    path('jobpost/<slug:slug>/delete', JobDeleteView.as_view(), name='jobdelete'),
    path('change_password/', ChangePassword.as_view(), name='password_change'),

    path('ajax/load-cities/', views.load_dis, name='ajax_load_district'),
    path('notify/', CompanyNotificationView.as_view(), name='companynotify'),

    # path('faq/create', FAQCreateView.as_view())
]

company/models.py
from django.utils.text import slugify

from custom_auth.models import User
from django.db import models
from home.models import *
from home.validators import *
from jobseeker.models import *
import random


# Create your models here.

class CompanyDetail(models.Model):
    company_name = models.CharField(max_length=25)
    province = models.ForeignKey(Provience, on_delete=models.CASCADE, related_name='companydetail_province')
    district = models.ForeignKey(District, on_delete=models.CASCADE, related_name='companydetail_district')
    company_address = models.CharField(max_length=50)
    company_type = models.CharField(max_length=50)
    contact_no = models.CharField(blank=True, max_length=9, validators=[phone_validation])
    mobile_no = models.CharField(blank=True, null=True, validators=[mobile_validation], max_length=10)
    company_image = ImageField()
    slug = models.SlugField()
    company_registration = models.DateField(null=True, blank=True, validators=[registration_date_validation])
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.company_name

    def save(self, *args, **kwargs):
        value = self.company_name
        self.slug = slugify(value, allow_unicode=True)
        super().save(*args, **kwargs)


class JobPost(models.Model):
    job_title = models.CharField(max_length=50)
    company = models.ForeignKey(CompanyDetail, on_delete=models.CASCADE, related_name='jobpost_company')
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    level_of_job = models.ForeignKey(Level, on_delete=models.CASCADE, related_name='jobpost_joblevel')
    vacancy = models.IntegerField(null=True)
    experience = models.CharField(max_length=25)
    education = models.ForeignKey(Education, models.CASCADE)
    salary = models.IntegerField(blank=True)
    negotiable = models.BooleanField(blank=True)
    job_type = models.ForeignKey(JobType, on_delete=models.CASCADE, related_name='jobpost_jobtype')
    description = models.TextField()
    requirement = models.TextField()
    pub_date = models.DateField(auto_now=True)
    deadline = models.DateField(validators=[deadline_registration])
    slug = models.SlugField()

    def __str__(self):
        return self.slug

    def save(self, *args, **kwargs):
        number = random.randint(0, 100000)

        value = self.company.company_name + self.job_title + str(number)
        self.slug = slugify(value, allow_unicode=True)
        super().save(*args, **kwargs)


class AppliedBySeeker(models.Model):
    job_title = models.ForeignKey(JobPost, on_delete=models.CASCADE)
    applicant_name = models.ForeignKey(Jobseeker, on_delete=models.CASCADE)
    applied_date = models.DateField(auto_now=True)
    status = models.BooleanField(blank=True)
    accepted = models.BooleanField(blank=True)

    def __str__(self):
        return self.applicant_name


class IPTracker(models.Model):
    user_ip = models.ForeignKey(User, null=True, blank=True, related_name="iptracker_user_ip", on_delete=models.CASCADE)
    job_ip = models.ForeignKey(JobPost, related_name="iptracker_job_ip", on_delete=models.CASCADE)
    ip_data = models.CharField(max_length=50)
    date_time=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.ip_data

company/views.py
from urllib import request

from django import forms
from django.contrib.auth.views import PasswordChangeView
from django.shortcuts import render, redirect
from django.urls import reverse_lazy

from company.models import *

# Create your views here.
from django.views.generic import *


class JobPostView(CreateView):
    template_name = 'new-post.html'
    model = JobPost
    fields = ['job_title', 'vacancy', 'experience', 'salary', 'negotiable', 'description', 'requirement', 'deadline']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        context['loc'] = CompanyDetail.objects.all()
        context['edu'] = Education.objects.all()
        context['jobs'] = JobPost.objects.all()
        context['jobtypes'] = JobType.objects.all()
        context['levels'] = Level.objects.all()

        context['com'] = CompanyDetail.objects.get(user_id=self.request.user)
        try:

            context['company_detail'] = CompanyDetail.objects.get(user_id=self.request.user)

        except Exception as e:
            print(e)
        return context

    def post(self, request, *args, **kwargs):
        form = self.get_form()

        if form.is_valid():
            cate = request.POST.get('cate')
            edu = request.POST.get('ed')
            j_level = request.POST.get('level')
            j_type = request.POST.get('jtype')
            category = Category.objects.get(category=cate)
            edu = Education.objects.get(education=edu)
            joblevel = Level.objects.get(job_level=j_level)
            jobtype = JobType.objects.get(job_type=j_type)
            sucess = form.save(commit=False)
            sucess.category_id = category.id
            sucess.education_id = edu.id
            sucess.job_type_id = jobtype.id
            sucess.level_of_job_id = joblevel.id

            user = request.user
            company = CompanyDetail.objects.all()
            for i in company:
                if user.id == i.user_id:
                    sucess.company_id = i.id

            sucess.save()

            return redirect('company:jobhome')

        else:
            print(form.errors)

        return redirect('home:home')


class CompanyBaseView(TemplateView):
    model = CompanyDetail
    template_name = '__company_base.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        try:
            context['com'] = CompanyDetail.objects.get(user_id=user)
        except Exception as e:
            print(e)
        return context


class CompanyHomeView(TemplateView):
    model = CompanyDetail
    template_name = 'dashboard.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user

        try:

            context['company_detail'] = CompanyDetail.objects.get(user_id=user)

        except Exception as e:
            print(e)
        return context


class CompanyProfileView(TemplateView):
    model = CompanyDetail
    template_name = 'company_profile.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user

        context['cdetail'] = CompanyDetail.objects.get(user_id=user)
        try:

            context['company_detail'] = CompanyDetail.objects.get(user_id=user)

        except Exception as e:
            print(e)
        return context


class CompanyJobListView(ListView):
    template_name = 'company_joblist_todelete_update.html'
    model = JobPost

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        print('company_joblist_ma kun user:', user)
        context['c_joblist'] = JobPost.objects.filter(company__user_id=user)
        try:

            context['company_detail'] = CompanyDetail.objects.get(user_id=user)

        except Exception as e:
            print(e)
        return context


class CompanyDetailView(CreateView):
    template_name = 'company_detail.html'
    model = CompanyDetail
    fields = ['company_name', 'province', 'district', 'company_address', 'company_type', 'contact_no', 'mobile_no',
              'company_image',
              'company_registration']

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        print('outise')
        if form.is_valid():
            print('inside')
            a = form.save(commit=False)

            a.user = request.user
            a.save()

            return redirect('company:jobpost')
        else:
            print(form.errors)

        return redirect('/custom/login')


class AppliedBySeekerView(CreateView):
    model = AppliedBySeeker
    fields = ['job_title', 'status', 'accepted']
    template_name = 'applied_job_seeker_list.html'

    def get(self, request, *args, **kwargs):

        user = request.user

        a = JobPost.objects.filter(company__user_id=user)
        n = CompanyDetail.objects.get(user_id=user)
        print('a ko value:', a)

        z = AppliedBySeeker.objects.all()

        context = {'jlist': a,
                   'sss': z,
                   'company_detail': n}

        return render(request, 'applied_job_seeker_list.html', context)

    def post(self, request, *args, **kwargs):
        form = self.get_form()

        if form.is_valid():
            a = form.save(commit=False)
            b = request.user.id

            jobsek = Jobseeker.objects.all()
            for i in jobsek:
                if i.user_id == b:
                    a.applicant_name_id = i.id

            a.save()

            return redirect('/')

        else:
            print({{form.errors}})

        return redirect('/custom/login')


class CompanyUpdateView(UpdateView):
    template_name = 'companydetail_update_form.html'
    model = CompanyDetail
    fields = ['company_name', 'province', 'district', 'company_address', 'company_type', 'contact_no', 'mobile_no',
              'company_image',
              'company_registration']
    success_url = reverse_lazy('company:cprofile')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user

        context['cdetail'] = CompanyDetail.objects.get(user_id=user)
        context['company_detail'] = CompanyDetail.objects.get(user_id=user)
        return context


class JobUpdateView(UpdateView):
    template_name = 'jobpost_update_form.html'
    model = JobPost

    fields = ['job_title', 'category', 'level_of_job', 'vacancy', 'experience', 'education', 'salary', 'negotiable',
              'job_type', 'description', 'requirement',
              'deadline']

    success_url = reverse_lazy('company:cprofile')


class JobDeleteView(DeleteView):
    model = JobPost
    template_name = 'jobpost_confirm_delete.html'
    success_url = reverse_lazy('company:jobpost')

    # def get(self, request, *args, **kwargs):
    #     return self.delete(request, *args, **kwargs)


class ChangePassword(PasswordChangeView):
    template_name = 'password_change.html'
    success_url = reverse_lazy('home:home')


# class FaqModelForm(forms.ModelForm):
#
#     class Meta:
#         model = JobPost
#         fields = '__all__'
#


#
# class FAQCreateView(CreateView):
#     model = JobPost
#     form_class = FaqModelForm
#     template_name = 'create_faq.html'
#     success_url = '/faq'

def load_dis(request):
    pro = request.GET.get('province')
    districts = District.objects.filter(provience_id=pro)
    return render(request, 'dis_dropdown_list_options.html', {'districts': districts})


class CompanyNotificationView(CreateView):
    template_name = 'notify.html'
    model = AppliedBySeeker
    fields = ['job_title', 'status', 'accepted']

    def get_context_data(self, *, object_list=None, **kwargs):
        user = self.request.user

        a = JobPost.objects.filter(company__user_id=user)
        z = AppliedBySeeker.objects.all()

        context = super().get_context_data(**kwargs)
        context['jlist'] = a
        context['sss'] = z

        try:

            context['company_detail'] = CompanyDetail.objects.get(user_id=user)

        except Exception as e:
            print(e)
        return context

    def post(self, request, *args, **kwargs):
        # form = self.get_form()
        print("outside form")

        b = request.user.id
        print(b)

        jobsek = AppliedBySeeker.objects.all()
        for i in jobsek:
            print("inside")
            print(i.job_title.company.user.id)
            a = AppliedBySeeker.objects.filter(job_title__company__user_id=b)
            getting = int(request.POST.get("hiddenid"))

            print("getting", getting)
            for j in a:
                z = j.job_title_id
                print("j ko ",z)
                if getting == z:
                    print("z ko value", z)
                    j.status = True
                    j.save()

            return redirect('company:companynotify')

        return redirect('/custom/login')

company/templates/__company_base.html
{% extends '_base.html' %}
{% load static %}
{% block content %}

    <link rel="stylesheet" href={% static "css/demo.css" %}>
    <link rel="stylesheet" href={% static "css/light-bootstrap-dashboard.css" %}>

    <section class="blog-posts-area section-gap">

    <div class="wrapper">

        <div class="sidebar" data-image="../assets/img/sidebar-5.jpg">
            <!--
        Tip 1: You can change the color of the sidebar using: data-color="purple | blue | green | orange | red"

        Tip 2: you can also add an image using data-image tag
    -->
            <div class="sidebar-wrapper">
                <div class="logo">
                    <a href="http://www.creative-tim.com" class="simple-text">
                        Welcome
                    </a>
                </div>
                <ul class="nav">

                    <li>
                        <a class="nav-link"
                           href="{% if request.user.id == company_detail.user_id %} {% url 'company:cprofile' %} {% else %} {% url 'company:companydetail' %}

{% endif %}">
                            <i class="nc-icon nc-circle-09"></i>
                            <p>company profile</p>
                        </a>
                    </li>
                    <li>
                        <a class="nav-link"
                           href="{% if request.user.id == company_detail.user_id %} {% url 'company:jobpost' %} {% else %} {% url 'company:companydetail' %}

{% endif %}">

                            <i class="nc-icon nc-tap-01"></i>
                            <p>Post a job</p>
                        </a>
                    </li>


                    <li>
                        <a class="nav-link"
                           href="{% if request.user.id == company_detail.user_id %} {% url 'company:cjoblist' %}
                               {% else %}{% url 'company:companydetail' %} {% endif %}">
                            <i class="nc-icon nc-notes"></i>
                            <p>Posted Job List</p>
                        </a>
                    </li>
                    <li>
                        <a class="nav-link" href="
                                {% if request.user.id == company_detail.user_id %}{% url 'company:apply' %}
                                    {% else %}{% url 'company:companydetail' %} {% endif %}">
                            <i class="nc-icon nc-paper-2"></i>
                            <p>Applied by user</p>
                        </a>
                    </li>
                    <li>


                        <a class="nav-link" href="./icons.html">
                            <i class="nc-icon nc-atom"></i>
                            <p>Icons</p>
                        </a>
                    </li>
                    <li>
                        <a class="nav-link" href="./maps.html">
                            <i class="nc-icon nc-pin-3"></i>
                            <p>Maps</p>
                        </a>
                    </li>
                    <li>
                        <a class="nav-link" href="{% url 'company:companynotify' %}">
                            <i class="nc-icon nc-bell-55"></i>
                            <p>Notifications</p>
                        </a>
                    </li>

                    <li>
                        <a class="nav-link" href="{% url 'company:password_change' %}">
                            <i class="nc-icon nc-key-25"></i>
                            <p>Change Password</p>
                        </a>
                    </li>
                    <li class="nav-item active active-pro">
                        <a class="nav-link active" href="upgrade.html">
                            <i class="nc-icon nc-alien-33"></i>
                            <p>Upgrade to PRO</p>
                        </a>
                    </li>
                </ul>
            </div>
        </div>

        <div class="main-panel">

            {% block company_dashboard %}
            {% endblock %}
        </div>
    </div>
    </section>

{% endblock %}

company/templates/apply_list.html
{% extends '_base.html' %}
{% block content %}
    <table>
        <tr>
            <th>Name</th>
            <th>Job Title</th>
            <th>Resume</th>
        </tr>
        {% for a in j_list %}
            <tr>
                <td>{{ a.job_title }}</td>
                <td>{{ a.applicant_name.user }}</td>
                <td>{{ a.job_title }}</td>
                <td>{{ a.applicant_name.resume }}</td>
            </tr>

        {% endfor %}
    </table>
{% endblock %}

company/templates/company_detail.html
{% extends '__company_base.html' %}
{% block company_dashboard %}






    <div class="offset-lg-2 col-lg-8">
        <h2 style="text-align: center; padding-top: 30px;">REGISTER YOUR COMPANY </h2>
        <div class="page-content bg-white">
            <!-- contact area -->
            <div class="content-block">
                <!-- Submit Resume -->
                <div class="section-full bg-white submit-resume content-inner-2">
                    <div class="container">
                        <form method="post" id="disForm" data-dis-url="{% url 'company:ajax_load_district' %}" enctype="multipart/form-data">
                            {% csrf_token %}


                            <div class="form-group">
                                <label>Company Name</label>
                                <input type="text" class="form-control" placeholder="Full company Name"
                                       id="company_name"
                                       name="company_name">
                            </div>

                            <div class="form-group">

                                <label>Province</label>
                                {{ form.province }}
                            </div>


                            <div class="form-group">

                                <label>District</label>
                                {{ form.district }}
                            </div>


                    <div class="form-group">
                        <label>Location</label>
                        <input type="text" class="form-control" placeholder="Your Full address" id="company_address"
                               name="company_address">

                    </div>


                    <div class="form-group">
                        <label>Type of Company</label>
                        <input type="text" class="form-control" placeholder="Type of company" id="company_type"
                               name="company_type">
                    </div>


                    <div class="form-group">
                        <label>Phone-no</label>
                        <input type="text" class="form-control" placeholder="phone no with Area code" id="contact_no"
                               name="contact_no" pattern="[0-9]{9}" title="enter valid phone no">
                    </div>

                    <div class="form-group">
                        <label>Mobile-no</label>
                        <input type="text" class="form-control" placeholder="***-*****-****" id="mobile_no"
                               name="mobile_no" pattern="[9][0-9]{9}" title="enter valid mobile no">
                    </div>


                    <div class="form-group">
                        <label>Company photo</label>
                        <input type="file" class="form-control" placeholder=".jpg/png" id="company_image"
                               name="company_image"
                               accept="image/jpeg">
                    </div>

                    <div class="form-group">
                        <label>Registration date</label>
                        <input type="date" class="form-control" placeholder="***-*****-****" id="company_registration"
                               name="company_registration">
                    </div>


                    <input type="submit" value="Submit" name="submit">
                    </form>
                </div>
            </div>
            <!-- Submit Resume END -->
        </div>
    </div>
    </div>

    <!-- Content END-->

     <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script>
    $("#id_province").change(function () {
      var url = $("#disForm").attr("data-dis-url");  // get the url of the `load_cities` view
      var provinceId = $(this).val();  // get the selected country ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'province': provinceId       // add the country id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_cities` view function
          $("#id_district").html(data);  // replace the contents of the city input with the data that came from the server
        }
      });

    });
  </script>


{% endblock %}

company/templates/company_joblist_todelete_update.html
{% extends '__company_base.html' %}

{% block company_dashboard %}


    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card strpied-tabled-with-hover">


                        <div class="card-body table-full-width table-responsive">
                            <table class="table table-hover table-striped">
                                <thead>
                                <th><h4>Job-Title</h4></th>
                                <th><h4>Job_level</h4></th>
                                <th><h4>Published-date</h4></th>
                                <th><h4></h4></th>

                                </thead>
                                <tbody>
                                {% for j in c_joblist %}

                                    <tr>
                                        <td>{{ j.job_title }}</td>
                                        <td>{{ j.level_of_job}}</td>
                                        <td>{{ j.pub_date }}</td>
                                        <td>

                                            <a href="{% url 'company:jobupdate' j %}"><input value="update"
                                                                                             type="submit"></a>

                                        </td>
                                        <td>

                                            <input value="Delete"
                                                   type="submit" style="color: red" data-toggle="modal"
                                                   data-target="#myModal">


                                        </td>

                                    </tr>


                                    <div id="myModal" class="modal fade" role="dialog">
                                        <div class="modal-dialog">

                                            <!-- Modal content-->
                                            <div class="modal-content">

                                                <div class="modal-header">
                                                    <h4 class="modal-title" style="alignment: left">
                                                        Delete {{ j.job_title }}</h4>
                                                    <button type="button" class="close" data-dismiss="modal">
                                                        &times;
                                                    </button>

                                                </div>
                                                <div class="modal-body">


                                                    <p>Are you sure you want to delete "{{ j.job_title }}"?</p>

                                                    <div class="modal-del-fo">
                                                        <form method="post"
                                                              action="{% url 'company:jobdelete' j %}">
                                                            {% csrf_token %}
                                                            <input type="submit" class="btn btn-danger"
                                                                   value="Yes">
                                                        </form>
                                                        <input type="submit" class="btn btn-default"
                                                               data-dismiss="modal"
                                                               value="No">

                                                    </div>

                                                </div>


                                            </div>

                                        </div>
                                    </div>
                                    <!-- End popup modal -->


                                {% endfor %}


                                </tbody>
                            </table>
                        </div>

                    </div>
                </div>

            </div>
        </div>
    </div>


{% endblock %}

company/templates/companydetail_update_form.html
{% extends '__company_base.html' %}
{% load crispy_forms_tags %}
{% block company_dashboard %}

    <div class="row">

                <div class="col-md-12 col-lg-8 mb-5">


                    <form method="post" enctype="multipart/form-data" id="upForm" data-dis-url="{% url 'company:ajax_load_district' %}">
                        {% csrf_token %}
                        {{ form | crispy }}
                        <input type="submit" value="UPDATE">

                    </form>
                </div>

                <div class="col-lg-4">
                    <div class="p-4 mb-3 bg-white">
                        <h3 class="h5 text-black mb-3">Contact Info</h3>
                        <p class="mb-0 font-weight-bold">Address</p>
                        <p class="mb-4">203 Fake St. Mountain View, San Francisco, California, USA</p>

                        <p class="mb-0 font-weight-bold">Phone</p>
                        <p class="mb-4"><a href="#">+1 232 3235 324</a></p>

                        <p class="mb-0 font-weight-bold">Email Address</p>
                        <p class="mb-0"><a href="#">youremail@domain.com</a></p>

                    </div>


                </div>
            </div>


     <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script>
    $("#id_province").change(function () {
      var url = $("#upForm").attr("data-dis-url");  // get the url of the `load_cities` view
      var provinceId = $(this).val();  // get the selected country ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'province': provinceId       // add the country id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_cities` view function
          $("#id_district").html(data);  // replace the contents of the city input with the data that came from the server
        }
      });

    });
  </script>

{% endblock %}

company/templates/password_change.html
{% extends "__company_base.html" %}
{% load crispy_forms_tags %}
{% block company_dashboard %}
    <div class="container">
        <div class="row justify-content-center align-items-center" style="height:80vh;">
            <div class="col-auto border p-3">
                {% if form.errors %}
                    <p class="bg-danger p-2">Incorrect password</p>
                {% endif %}
                {% if next %}
                    {% if user.is_authenticated %}

                        <p class="bg-warning p-1">Your account doesn't have access.</p>
                    {% else %}
                        <p class="bg-secondary">Please login to see this page.</p>
                    {% endif %}
                {% endif %}
                <form method="post" action="{% url 'company:password_change' %}">
                    {% csrf_token %}
                    {{ form | crispy}}
                    <input class="mt-3" type="submit" value="Change Password"/>
                    <input type="hidden" name="next" value="{{ next }}"/>
                </form>
            </div>
        </div>
    </div>
{% endblock %}