JobPortal/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('home.urls')),
                  path('custom/', include('custom_auth.urls')),
                  path('cms/', include('cms.urls')),
                  path('company/', include('company.urls')),
                  path('jobseeker/', include('jobseeker.urls')),
                  path('blog/',include('blog.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path

from blog.views import *

app_name = 'blog'

urlpatterns = [

    path('', BlogView.as_view(), name='blog'),
    path('single/<slug:slug>', SingleBlogView.as_view(), name='single_blog'),

    path('single/<slug:slug>/update', SingleBlogView.as_view(), name='single_update'),
    path('comment/', CommentView.as_view()),
]

cms/urls.py
from django.urls import path
from .views import *

app_name = 'cms'

urlpatterns = [

    path('', AboutUsView.as_view(), name='about'),
    path('contact/', ContactUsView.as_view(), name='contact'),

]

company/urls.py
from django.urls import path

from company import views
from company.views import *

app_name = 'company'

urlpatterns = [
    path('jobpost/', JobPostView.as_view(), name='jobpost'),
    path('jobpost/c_list', CompanyJobListView.as_view(), name='cjoblist'),
    path('jobpost/chome', CompanyHomeView.as_view(), name='jobhome'),
    path('jobpost/base', CompanyBaseView.as_view(), name='cbase'),
    path('profile/', CompanyProfileView.as_view(), name='cprofile'),

    path('companydetail/', CompanyDetailView.as_view(), name='companydetail'),
    path('companydetail/<slug:slug>/update', CompanyUpdateView.as_view(), name='cupdate'),
    path('apply/', AppliedBySeekerView.as_view(), name='apply'),
    path('jobpost/<slug:slug>/update', JobUpdateView.as_view(), name='jobupdate'),
    path('jobpost/<slug:slug>/delete', JobDeleteView.as_view(), name='jobdelete'),
    path('change_password/', ChangePassword.as_view(), name='password_change'),

    path('ajax/load-cities/', views.load_dis, name='ajax_load_district'),
    path('notify/', CompanyNotificationView.as_view(), name='companynotify'),

    # path('faq/create', FAQCreateView.as_view())
]

home/urls.py
from django.urls import path
from home.views import *

app_name = "home"

urlpatterns = [

    path('', IndexView.as_view(), name='home'),
    path('search/', SearchView.as_view(), name='search'),
    path('faq/', FaqView.as_view(), name='faq'),
    path('jobdetail/<slug:slug>/', JobDetailView.as_view(), name='jobdetail'),
    path('list/', JobListView.as_view(), name='joblist'),
    path('location/<slug:slug>',ByLocationView.as_view(),name='by_location')


]

jobseeker/urls.py
from django.urls import path

from jobseeker import views
from jobseeker.views import *

app_name = "jobseeker"

urlpatterns = [

    path('category/', JobSeekerCategoryView.as_view(), name='jobcategory'),

    path('seekerdetail/', JobSeekerDetailView.as_view(), name='seekerdetail'),
    path('seekertable/', JobsekkerTableView.as_view(), name='table'),
    path('seekerdashboard/', SeekerDashboardView.as_view(), name='sdhome'),
    path('seekerdashboard/base', SeekerIndexView.as_view(), name='sindex'),
    path('seekerdetail/<slug:slug>/update', UserProfileUpdateView.as_view(), name='supdate'),
    path('change_password/', ChangePassword.as_view(), name='password-change'),
    path('ajax/load-dis/', views.load_province, name='job_ajax_load_district'),

]

templates/_base.html
{% load static %}
{% load thumbnail %}
<!DOCTYPE html>
<html lang="zxx" class="no-js">
<head>
    <!-- Mobile Specific Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Favicon-->
    <link rel="shortcut icon" href="img/fav.png">
    <!-- Author Meta -->
    <meta name="author" content="codepixer">
    <!-- Meta Description -->
    <meta name="description" content="">
    <!-- Meta Keyword -->
    <meta name="keywords" content="">
    <!-- meta character set -->
    <meta charset="UTF-8">
    <!-- Site Title -->
    <title>Jagir Khulyo</title>

    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">
    <!--
    CSS
    ============================================= -->
    <link rel="stylesheet" href="{% static 'css/linearicons.css' %}">
    <link rel="stylesheet" href={% static "css/font-awesome.min.css" %}>
    <link rel="stylesheet" href={% static "css/bootstrap.css" %}>
    <link rel="stylesheet" href={% static "css/magnific-popup.css" %}>
    <link rel="stylesheet" href={% static "css/nice-select.css" %}>
    <link rel="stylesheet" href={% static "css/animate.min.css" %}>
    <link rel="stylesheet" href={% static "css/owl.carousel.css" %}>
    <link rel="stylesheet" href={% static "css/main.css" %}>
    <link rel="stylesheet" href={% static "css/style.css" %}>


</head>

<body>
<header id="header" id="home">
    <div class="container">
        <div class="row align-items-center justify-content-between d-flex">
            <div id="logo">
                <a href=""><img src="{% static 'img/jk.png' %}" height="70px" width="100px"/></a>
            </div>

            <nav id="nav-menu-container">
                <ul class="nav-menu">
                    <li class="menu-active"><a href="{% url 'home:home' %}">HOME</a></li>
                    <li><a href="{% url 'cms:about' %}">ABOUT US</a></li>
                    <li><a href="{% url 'cms:contact' %}">CONTACT US</a></li>
                    {% if request.user.is_authenticated and request.user.role == 'jobseeker' %}



                        <li class="menu-has-children"><a href="">JOBSEEKER</a>
                            <ul>

                                <li><a href="{% url 'home:joblist' %}">Browse Jobs</a></li>


                            </ul>
                        </li>
                        <li><a href="{% url 'blog:blog' %}">BLOGS</a></li>

                        <li><a href="{% url 'jobseeker:sindex' %}">MY Account</a></li>
                        <li><a href="{% url 'custom_auth:logout' %}">Logout</a></li>


                    {% elif request.user.is_authenticated and request.user.role == 'company' %}
                        <li class="menu-has-children"><a href="">COMPANY</a>
                            <ul>

                                <li>
                                    <a href="{% if user.id == company_detail.user_id %} {% url 'company:jobpost' %} {% else %} {% url 'company:companydetail' %}

{% endif %}">Post Job</a></li>


                            </ul>
                        </li>
                        <li><a href="{% url 'blog:blog' %}">BLOGS</a></li>

                        <li><a href="{% url 'company:jobhome' %}">My Account</a></li>
                        <li><a href="{% url 'custom_auth:logout' %}">Logout</a></li>


                    {% else %}
                        <li><a href="{% url 'blog:blog' %}">BLOGS</a></li>


                        {% if user.is_authenticated %}
                            <li><a href="{% url 'custom_auth:logout' %}">Logout</a></li>


                        {% else %}
                            <li><a href="{% url 'custom_auth:register' %}">Signup</a></li>
                            <li><a href="{% url 'custom_auth:login' %}">Login</a></li>


                        {% endif %}
                    {% endif %}
                </ul>
            </nav><!-- #nav-menu-container -->

        </div>
    </div>
</header><!-- #header -->

{% block content %}{% endblock %}

<!-- start footer Area -->
<footer class="footer-area p-5">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 ">
                <div class="single-footer-widget">
                    <h6>JOBSEEKER</h6>
                    <ul class="footer-nav">
                        <li><a href="{% url 'custom_auth:register' %}">Register Jobseeker</a></li>
                        <li><a href="{% url 'custom_auth:login' %}">Login into Account</a></li>
                        <li><a href="
                                {% if request.user.role == 'jobseeker' %}{% url 'jobseeker:sdhome' %}{% else %}{% url 'custom_auth:login' %}{% endif %}">Apply
                            for Job</a></li>
                        <li><a href="{% url 'home:faq' %}">FAQ</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-4"><img src="{% static 'img/jk.png' %}" height="200px" width="300px"/>
            </div>
            <div class="col-lg-4 ">
                <div class="single-footer-widget text-right">
                    <h6>Company</h6>
                    <ul class="footer-nav">
                        <li><a href="{% url 'custom_auth:register' %}">Register company</a></li>
                        <li><a href="{% url 'custom_auth:login' %}">Login into Account</a></li>
                        <li><a href="

                                {% if request.user.role == 'company' %}{% url 'company:jobpost' %}{% else %}{% url 'custom_auth:login' %}{% endif %}">Post
                            your job</a>
                        </li>
                        <li><a href="{% url 'home:faq' %}">FAQ</a></li>
                    </ul>
                </div>
            </div>


        </div>


    </div>

</footer>
<!-- End footer Area -->

<script src={% static "js/vendor/jquery-2.2.4.min.js" %}></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script src={% static "js/vendor/bootstrap.min.js" %}></script>
<script type="text/javascript"
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA"></script>
<script src={% static "js/easing.min.js" %}></script>
<script src={% static "js/hoverIntent.js" %}></script>
<script src={% static "js/superfish.min.js" %}></script>
<script src={% static "js/jquery.ajaxchimp.min.js" %}></script>
<script src={% static "js/jquery.magnific-popup.min.js" %}></script>
<script src={% static "js/owl.carousel.min.js" %}></script>
<script src={% static "js/jquery.sticky.js" %}></script>
<script src={% static "js/jquery.nice-select.min.js" %}></script>
<script src={% static "js/parallax.min.js" %}></script>
<script src={% static "js/mail-script.js" %}></script>
<script src={% static "js/main.js" %}></script>
<script src={% static "js/demo.js" %}></script>
<script src={% static "js/light-bootstrap-dashboard.js" %}></script>
<script src="{% static 'js/contactapp.js' %}"></script>

</body>
</html>